server {
    listen 443 ssl default_server;
    listen [::]:443 ssl default_server;
    http2 on;

    server_name plzbuyme.shop www.plzbuyme.shop;

    ssl_certificate /etc/letsencrypt/live/plzbuyme.shop/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/plzbuyme.shop/privkey.pem;

    root /var/www/plzbuyme;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://127.0.0.1:5081;
    }

    location /media/ {
        proxy_pass http://127.0.0.1:5090;
    }
}
